build: off
deploy: off

test_script:
- set base_path=C:/Program Files/7-Zip;C:/Program Files/AppVeyor/BuildAgent;C:/Program Files/Git/cmd;C:/Program Files (x86)/GNU/GnuPG/pub;C:/Windows/system32;C:/Windows

- appveyor DownloadFile https://ci.appveyor.com/api/projects/MSP-Greg/ruby-loco/artifacts/ruby_trunk.7z -FileName C:/ruby_trunk.7z
- 7z x C:/ruby_trunk.7z -oC:/ruby_trunk

- echo off
- set PATH=C:/ruby200-x64/bin;%base_path%
- xcopy C:\Greg\ruby26-x64\lib\ruby\gems\2.6.0\gems\bundler-1.16.2           C:\Greg\ruby26-x64\lib\ruby\gems\2.6.0\gems\bundler-1.16.2 /y /s /q 
- copy  C:\Greg\ruby26-x64\lib\ruby\gems\2.6.0\specifications\bundler-1.16.2 C:\Greg\ruby26-x64\lib\ruby\gems\2.6.0\\specifications\bundler-1.16.2 /y /s /q
- ps: >-
    if ((gem query -i bundler -v 1.16.2) -eq $False) {
      gem update bundler -N
    }

- set PATH=C:/ruby21-x64/bin;%base_path%
- ps: >-
    gem install rubygems-update ; update_rubygems ;
    if ((gem query -i bundler -v 1.16.2) -eq $False) {
      gem update bundler -N
    }


- set PATH=C:/ruby22-x64/bin;%base_path%
- ps: >-
    if ((gem query -i bundler -v 1.16.2) -eq $False) {
      gem update bundler -N
    }


- set PATH=C:/ruby23-x64/bin;%base_path%
- ps: >-
    if ((gem query -i bundler -v 1.16.2) -eq $False) {
      gem update bundler -N
    }
