build:  off
deploy: off

test_script:
  - mklink /d C:\git "C:\Program Files\Git"
  - set base_path=C:/msys64/usr/bin;C:/Program Files/7-Zip;C:/Program Files/AppVeyor/BuildAgent;C:/Git/cmd;C:/Program Files (x86)/GNU/GnuPG/pub;C:/Windows/system32

  - set PATH=C:/ruby24-x64/bin;%base_path%
  - appveyor DownloadFile https://dl.bintray.com/msp-greg/ruby_windows/ruby_trunk_32.7z -FileName C:\ruby_trunk_32.7z &
      7z x C:\ruby_trunk_32.7z -oC:\ruby_trunk_32 & C:\ruby_trunk_32\trunk_install_32.cmd )
  - set PATH=C:/ruby_trunk_32/bin;%base_path% & cd \projects\appveyor-testing\test
  - echo ----------------------------------------------------------------------------- trunk_32 openssl test
  - ruby --disable-gems -v runner.rb -I. -I./lib -v --show-skip openssl

  - set PATH=C:/ruby24-x64/bin;%base_path%
  - appveyor DownloadFile https://dl.bintray.com/msp-greg/ruby_windows/ruby_trunk.7z -FileName C:\ruby_trunk.7z &
      7z x C:\ruby_trunk.7z -oC:\ruby_trunk & C:\ruby_trunk\trunk_install.cmd )
  - set PATH=C:/ruby_trunk/bin;%base_path% & cd \projects\appveyor-testing\test
  - echo ----------------------------------------------------------------------------- trunk_64 openssl test
  - ruby --disable-gems -v runner.rb -I. -I./lib -v --show-skip openssl
