build:  off
deploy: off

init:
  - mklink /d C:\git "C:\Program Files\Git"
  - set BASE_PATH=C:/Program Files/7-Zip;C:/Program Files/AppVeyor/BuildAgent;C:/git/cmd;C:/Program Files (x86)/GNU/GnuPG/pub;C:/msys64/usr/bin;C:/Windows/system32;C:\Windows;

install:
  - set PATH=C:/ruby200/bin;%BASE_PATH%
  - ruby -v
  - gem -v
    gem install rake -v ">= 20.0" & exit 0

  - set PATH=C:/ruby200-x64/bin;%BASE_PATH%
  - ruby -v
  - gem -v
    gem install rake -v ">= 20.0" & exit 0
  
  - set PATH=C:/ruby21/bin;%BASE_PATH%
  - ruby -v
    @gem -v
    gem install rake -v ">= 20.0" & exit 0

  - set PATH=C:/ruby21-x64/bin;%BASE_PATH%
  - ruby -v
  - gem -v
  - gem install rake -v ">= 20.0" & exit 0
  
  - set PATH=C:/ruby22/bin;%BASE_PATH%
  - ruby -v
  - gem -v
  - gem install rake -v ">= 20.0" & exit 0

  - set PATH=C:/ruby22-x64/bin;%BASE_PATH%
  - ruby -v
  - gem -v
  - gem install rake -v ">= 20.0" & exit 0

  - set PATH=C:/ruby23/bin;%BASE_PATH%
  - ruby -v
  - gem -v
  - gem install rake -v ">= 20.0" & exit 0

  - set PATH=C:/ruby23-x64/bin;%BASE_PATH%
  - ruby -v
  - gem -v
  - gem install rake -v ">= 20.0" & exit 0

  - set PATH=C:/ruby24-x64/bin;%BASE_PATH%
  - ruby -v
  - gem -v
  - gem install rake -v ">= 20.0" & exit 0

  - appveyor DownloadFile https://dl.bintray.com/msp-greg/ruby_windows/ruby_trunk.7z -FileName C:\ruby_trunk.7z &
      7z x C:\ruby_trunk.7z -oC:\ruby_trunk & C:\ruby_trunk\trunk_install.cmd )
  - set PATH=C:/ruby_trunk/bin;%BASE_PATH%
  - ruby -v
  - gem -v
  - gem install rake -v ">= 20.0" & exit 0
